### ISSUE TITLE
Please update the download path of the 512*512 model

### ISSUE THREAD

**Issue by uk9921** [nerdyrodent/CLIP-Guided-Diffusion#4]
Thank you for your open source code : ), but I failed to download the 512x512_diffusion_uncond_finetune_008100.pt. I noticed that the download path of the model has been updated to `curl -OL https://v-diffusion.s3.us-west-2.amazonaws.com/512x512_diffusion_uncond_finetune_008100.pt` in the corresponding [colab](https://colab.research.google.com/drive/1QBsaDAZv8np29FPbvjffbE1eytoJcsgA#scrollTo=7zAqFEykBHDL). 
Do you need to update the README or setup.sh?

**Comment by nerdyrodent** [comment]
Thanks, I've updated to use the new URL
