### ISSUE TITLE
512x512 model no longer available  at address specified in setup.sh

### ISSUE THREAD

**Issue by jdagdelen** [nerdyrodent/CLIP-Guided-Diffusion#7]
Looks like the S3 bucket has been taken down

**Comment by jdagdelen** [comment]
I believe it can be replaced with https://the-eye.eu/public/AI/models/512x512_diffusion_unconditional_ImageNet/512x512_diffusion_uncond_finetune_008100.pt

**Comment by nerdyrodent** [comment]
Thanks for letting me know!
